buildpacks:
  - name: nodejs-engine
    provider: heroku
    version: v1.5.6
  - name: node
    provider: digitalocean
    version: v0.4.0
  - name: procfile
    provider: digitalocean
    version: v0.0.4
  - name: custom
    provider: digitalocean
    version: v0.1.2